config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :categories
  resources :lessons
  resources :words
  resources :answers

  resources :categories do
    resources :words
  end

  resources :lessons do
    resources :answers
  end

  root "static_pages#home"
  get "static_pages/home"
  get "/about", to: "static_pages#about"
  get "/contact", to: "static_pages#contact"
  get "/signup", to: "users#new"
  get "/login", to: "sessions#new"
  delete "/logout", to: "sessions#destroy"
end

app/models/user.rb
class User < ApplicationRecord
    validates :name, presence: true, length: { maximum: 50 }
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :email, presence: true,
                      format: { with: VALID_EMAIL_REGEX }, 
                      uniqueness: { case_sensitive: false }
    has_secure_password
    validates :password, length: { minimum: 6 }

    
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def new
        @user = User.new
    end

    def create
        @user = User.new(user_params)
        if @user.save
          flash[:session] = "Saved Successfully"
          redirect_to login_url
        else
          flash[:danger] = "Invalid content. Try Again."
          render 'new'
        end
    end

    def index
        @user = User.all
        @users = User.paginate(page: params[:page], per_page: 9 )
    end

    def show
        @user = User.find(params[:id])
    end
    
    def destroy
        User.find(params[:id]).destroy
        redirect_to users_path
    end
     
    def edit
        @user = User.find(params[:id])
    end

    def update
        @user = User.find(params[:id])
        if @user.update_attributes(user_params)
           flash[:session] = "Saved Successfully"
           redirect_to @user
        else
           flash[:danger] = "Invalid content. Try Again."
           render 'edit'
        end
    end
    
private

    def user_params
        params.require(:user).permit(:name, :email, :password, :password_confirmation, :is_admin)
    end

    def current_user
        @user = User.find(params[:id])
        redirect_to(root_url) unless current_user?(@user)
    end
    
end

app/helpers/users_helper.rb
module UsersHelper
    def gravatar_for(user, options = { size: 50 })
        gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
        size = options[:size]
        gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?d=https://www.sui-sai.jp/illust/2014/05/19/img/010.jpg?s=#{size}"
        image_tag(gravatar_url, alt: user.name, class: "gravatar", width: 80, height:80)
    end  
end

app/views/users/_form.html.erb
<div class="container">
       <%= form_for(@user) do |f| %>
           <%= f.label :name %>
           <%= f.text_field :name, class: "form-control" %>

           <%= f.label :email %>
           <%= f.text_field :email, class: "form-control" %>

           <%= f.label :password %>
           <%= f.password_field :password, class: "form-control" %>

           <%= f.label :password_confirmation, "Confirmation" %>
           <%= f.password_field :password_confirmation, class: "form-control" %>

           <%= f.hidden_field :is_admin, value: 0 %>
           <%= f.submit class: "btn btn-block btn-primary" %>
       <% end %>
</div>

app/views/users/edit.html.erb
<%= provide(:title, "Edit") %>
<div class="mt-4">
   <h1 class="text-center">Edit your profile</h1>
   <div class="container">
      <%= render 'form' %>  
   </div>
</div>

app/views/users/index.html.erb
<% provide(:title, 'List of Users') %>
<div class="container">
  <div class="row d-flex justify-content-center mt-5">
    <%= will_paginate %>
  </div>
      <div class="row mt-3 mx-auto justify-content-center">
            <% @users.each do |user| %>
                <div class="card border-success mx-auto my-5" style="width: 20rem;">
                    <div class="card-body text-success">
                       <h5 class="card-title"><%= gravatar_for user, size: 52 %><%= link_to user.name, user %></h5>
                       <%= link_to raw("<i class='fa fa-trash text-danger'></i>"), user_path(user), class: "text-danger", method: :delete, data: { confirm: "You sure?" } unless !current_user?(user)%>
                    </div>
                </div>
            <% end %>    
      </div>
   <div class="row d-flex justify-content-center">
    <%= will_paginate %>
   </div>
</div>           

app/views/users/login.html.erb
<% provide(:title, 'Login') %>
<div class="form content">
   <h1 class="text-center">Login</h1>
   <div class="container">
       <%= form_for(:session, url: sessions_path) do |f| %>
           <%= f.label :email %>
           <%= f.text_field :email, class: "form-control" %>

           <%= f.label :password %>
           <%= f.password_field :password, class: "form-control" %>

           <%= f.submit "Login", class: "btn btn-block btn-primary" %>
       <% end %>
       <p>New here? <%= link_to "Sign up now!", signup_path %></p>
   </div>
</div>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<div class="form">
   <h1 class="text-center mt-5">Sign up</h1>
    <%= render 'form' %>  
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row mt-5 mx-auto justify-content-center">
  <div class="card text-white bg-warning mb-3" style="max-width: 20rem;">
    <div class="card-header text-center"><strong>User Information</strong></div>
      <div class="card-body">
        <h5 class><div class="container">

<div class="card-title text-center"><%= gravatar_for @user %></h5>
        <h4 class="text-center"><%= @user.name %></h4>
      <% if logged_in? && current_user.is_admin? %>
        <div class="text-center">
         <%= link_to "Admin Dashbourd", categories_path, class: "btn btn-outline-success" %>
        </div>
      <% end %>
        <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
      </div>
  </div>
    <div class="ml-5">
      <div class="card text-white bg-success mb-3" style="max-width: 60rem;">
        <div class="card-header text-center"><strong>User Activity</strong></div>
          <div class="card-body">
            <h5 class="card-title">Danger card title</h5>
            <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
          </div>
      </div>
    </div>      
</div>