config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :categories
  resources :lessons
  resources :words
  resources :answers

  resources :categories do
    resources :words
  end

  resources :lessons do
    resources :answers
  end

  root "static_pages#home"
  get "static_pages/home"
  get "/about", to: "static_pages#about"
  get "/contact", to: "static_pages#contact"
  get "/signup", to: "users#new"
  get "/login", to: "sessions#new"
  delete "/logout", to: "sessions#destroy"
end

app/models/word.rb
class Word < ApplicationRecord
    belongs_to :category
    validates :category_id, presence: true
    validates :content, presence: true

    has_many :choices, dependent: :destroy
    accepts_nested_attributes_for :choices, allow_destroy: true
 end

app/controllers/words_controller.rb
class WordsController < ApplicationController
  def new
    @word = Word.new
    3.times{ @word.choices.build }
  end

  def create
    @word = Word.new(word_params)
    if @word.save
      flash[:success] = "Saved Successfully"
      redirect_to category_words_path(@word.category_id)
    else
      flash[:danger] = @word.errors.full_messages.to_sentence
      redirect_back(fallback_location: root_path)
    end
  end

  def index
    @category = Category.find(params[:category_id])
    @word = Word.paginate(page: params[:page], per_page: 5 )
  end

  def edit
    @word = Word.find(params[:id])
  end

  def update
    @word = Word.find(params[:id])
    if @word.update_attributes(word_params)
      flash[:success] = "Saved Successfully"
      redirect_to category_words_path(@word.category_id)
    else
      flash[:danger] = @word.errors.full_messages.to_sentence
      redirect_back(fallback_location: root_path)
    end
  end

  def destroy
    @word = Word.find(params[:id]).destroy
    if @word
      flash[:danger] = "Deleted!"
    else
      flash[:warning] = "Delete Failed"
    end
    redirect_back(fallback_location: root_path)
  end

  def categories
    @category = Category.paginate(page: params[:page], per_page: 10)
  end

  private
  def word_params
    params.require(:word).permit(:category_id, :content, choices_attributes: [ :id, :word_id, :content, :correct ])
  end
end

app/helpers/words_helper.rb
module WordsHelper
end

app/views/words/_edit_form.html.erb
<div class="container">
  <%= form_for(@word) do |f| %>
    <%= f.hidden_field :category_id, value: params[:category_id] %>
           <%= f.label :Word %>
           <%= f.text_field :content, class: "form-control" %>
              <%= f.fields_for :choices do |choice| %>
                  <fieldset>
                    <%= choice.hidden_field :id %>
                    <%= choice.hidden_field :word_id %>
                      <%= choice.label :content, "Choice", class: "mt-4" %><br/>
                      <%= choice.text_field :content, class: "form-control" %>
                      <%= choice.check_box :correct, class: "left" %>
                      <%= choice.label :content, "Correct Answer" %>
                  </fieldset>
              <% end %>
           <%= f.submit "Update Word", class: "btn btn-outline-danger w-50 offset-3 col-9 offset-2 mt-4" %>
  <% end %>
</div>

app/views/words/_form.html.erb
<div class="container">
  <%= form_for(@word) do |f| %>
    <%= f.hidden_field :category_id, value: params[:category_id] %>
           <%= f.label :Word %>
           <%= f.text_field :content, class: "form-control" %>
              <%= f.fields_for :choices do |choice| %>
                  <fieldset>
                      <%= choice.label :content, "Choice", class: "mt-4" %><br/>
                      <%= choice.text_field :content, class: "form-control" %>
                      <%= choice.check_box :correct, class: "left" %>
                      <%= choice.label :content, "Correct Answer" %>
                  </fieldset>
              <% end %>
           <%= f.submit "Create Word", class: "btn btn-outline-danger w-50 offset-3 col-9 offset-2 mt-4" %>
  <% end %>
</div>

app/views/words/_menu.html.erb
    <div class="card" style="width: 10rem; height: 10rem">
        <div class="card-header">
            <%= link_to "Dashboard", categories_path %>
        </div>
            <ul class="list-group list-group-flush">
                <li class="list-group-item">
                    <%= link_to "Categories", categories_path %>
                </li>
                <li class="list-group-item">
                    <%= link_to "Users" %>
                </li>
                <li class="list-group-item text-center">
                    <%= link_to "Back", :back, class: "btn btn-outline-info w-10" %>
                </li>
            </ul>
    </div>

app/views/words/categories.html.erb
<%= provide(:title, "Categories") %>
<div class="row mt-5 mx-auto justify-content-center">
    <%= render 'menu' %>
    <div class="ml-5">
        <div class="card text-primary bg-light" style="max-width: 60rem;">
            <div class="row card-header">
                <h3 class="offset-1">Categories</h3>
                <%= link_to "Create new category", new_category_path, class: "btn btn-outline-danger offset-md-5" %>
            </div>
            <div class="card-body">
                <div class="container">
                    <table class="table table-striped">
                        <thead>
                            <tr>
                                <th scope="col">Title</th>
                                <th scope="col">Description</th>
                                <th scope="col">Created Date</th>
                                <th colspan="4"></th>
                            </tr>
                        </thead>
                        <tbody>
                        <% @category.each do |category| %>
                            <tr>
                                <td><%= link_to category.title, words_path %></td>
                                <td><%= category.description %></td>
                                <td><%= category.created_at.to_date%></td>
                          <% if logged_in? && current_user.is_admin? %> 
                                <td><%= link_to raw("<i class='fas fa-pen text-success'></i>"), edit_category_path(category) %></td>
                                <td><%= link_to raw("<i class='fa fa-trash text-danger'></i>"), categories_path, method: :delete, data: { confirm: "You sure?" } %></td>
                          <% end %>
                            </tr>
                        <% end %>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>   
    </div>
</div>
<div class="row d-flex justify-content-center mt-3">
    <%= will_paginate @category%>
</div> 

app/views/words/dashboard.html.erb
<%= provide(:title, "Dashboard") %>
<div class="row mt-5 mx-auto justify-content-center">
    <%= render 'menu' %>
    <div class="ml-5">
      <div class="card text-primary bg-light" style="width: 60rem;">
        <div class="card-header text-center"><strong>User Activity</strong></div>
          <div class="card-body">
            <h5 class="card-title">ddd</h5>
            <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
          </div>
      </div>
    </div>      
</div>
</div>

app/views/words/edit.html.erb
<%= provide(:title, "Create Word") %>
<div class="text-center mt-4">
    <h1>Edit a word</h1>
</div>
<%= render 'edit_form' %>

app/views/words/index.html.erb
<%= provide(:title, "Words") %>
<div class="row mt-5 mx-auto justify-content-center">
    <%= render 'menu' %>
        <div class="ml-5">
            <div class="card text-primary bg-light" style="width: 60rem;">
                <div class="row card-header">
                    <h3 class="offset-1">Words for the <%= @category.title %> lessons</h3>
                    <%= link_to "Create new word", new_category_word_path, class: "btn btn-outline-danger offset-1" %>
                </div>
                <div class="card-body">
                    <div class="container">
                        <table class="table table-striped">
                            <thead>
                                <tr>
                                    <th scope="col">Word</th>
                                    <th scope="col">Answer</th>
                                    <th scope="col">Created date</th>
                                    <th colspan="3"></th>
                                </tr>
                            </thead>
                            <tbody>
                            <% @word.each do |word| %>
                                <tr>
                                    <td><%= word.content %></td>
                                    <td>
                                        <% for choice in word.choices%>
                                            <% if choice.correct%> <%#show only answer%>
                                                <%= choice.content%>
                                            <% end %>
                                        <% end %>
                                    </td>
                                    <td><%= word.created_at.to_date%>
                                        <% if logged_in? && is_admin? %> 
                                            <td><%= link_to raw("<i class='fas fa-pen text-success'></i>"), edit_category_word_path(@category.id, word.id) %></td>
                                            <td><%= link_to raw("<i class='fa fa-trash text-danger'></i>"),  category_word_path(@category.id, word.id), method: :delete, data: { confirm: "You sure?" } %></td>
                                    </td>
                              <% end %>
                                </tr>
                            <% end %>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
</div>
<div class="row d-flex justify-content-center mt-3">
    <%= will_paginate @word%>   
</div>

app/views/words/new.html.erb
<%= provide(:title, "Create Word") %>
<div class="text-center mt-4">
    <h1>Create a new word</h1>
</div>
<%= render 'form' %>

app/views/words/show.html.erb
<h1>Admins#show</h1>
<p>Find me in app/views/admins/show.html.erb</p>