config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :categories
  resources :lessons
  resources :words
  resources :answers

  resources :categories do
    resources :words
  end

  resources :lessons do
    resources :answers
  end

  root "static_pages#home"
  get "static_pages/home"
  get "/about", to: "static_pages#about"
  get "/contact", to: "static_pages#contact"
  get "/signup", to: "users#new"
  get "/login", to: "sessions#new"
  delete "/logout", to: "sessions#destroy"
end

app/models/category.rb
class Category < ApplicationRecord
    validates :title, :description, presence: true
    has_many :words, dependent: :delete_all
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :is_admin?

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      flash[:success] = "Saved Successfully"
      redirect_to categories_path
    else
      flash[:danger] = @category.errors.full_messages.to_sentence
      render "create"
    end
  end

  def show
    @category = Category.find(params[:id])
  end

  def index
    @category = Category.paginate(page: params[:page], per_page: 10 )
  end

  def edit
    @category = Category.find_by(params[:id])
  end

  def update
    @category = Category.find_by(params[:id])
    if @category.update_attributes(category_params)
      flash[:success] = "Saved Successfully"
      redirect_to categories_path
    else
      flash[:danger] = "Editing failed"
      render "edit"
    end
  end

  def destroy
    Category.find(params[:id]).destroy
    redirect_to categories_path
  end

  private
  def category_params
    params.require(:category).permit(:title, :description)
  end 
end

app/helpers/category_helper.rb
module CategoryHelper
end

app/views/categories/_form.html.erb
<div class="container">
       <%= form_for(@category) do |f| %>
           <%= f.label :Title %>
           <%= f.text_field :title, class: "form-control" %>

           <%= f.label :Description %>
           <%= f.text_field :description, class: "form-control" %>

           <%= f.submit class: "btn btn-outline-danger w-50 offset-3 col-9 offset-2 mt-4" %>
       <% end %>
</div> 

app/views/categories/edit.html.erb
<%= provide(:title, "Edit") %>
<div class="mt-4">
   <h1 class="text-center">Edit lessons</h1>
   <div class="container">
      <%= render 'form' %>  
   </div>
</div>

app/views/categories/index.html.erb
<%= provide(:title, "index") %>
<div class="row mt-5 mx-auto justify-content-center">
  <div class="card" style="width: 10rem; height: 10rem">
    <div class="card-header">
        <%= link_to "Dashboard", categories_path %>
    </div>
          <ul class="list-group list-group-flush">
              <li class="list-group-item">
                  <%= link_to "Categories", categories_path %>
              </li>
              <li class="list-group-item">
                  <%= link_to "Users" %>
              </li>
              <li class="list-group-item text-center">
                  <%= link_to "Back", :back, class: "btn btn-outline-info w-10" %>
              </li>
          </ul>
  </div>

  <div class="ml-5">
      <div class="card text-primary bg-light" style="width: 60rem;">
          <div class="row card-header">
            <h3 class="offset-1">Lessons</h3>
            <%= link_to "Create new category", new_category_path, class: "btn btn-outline-danger offset-md-7" %>
          </div>
          <div class="card-body">
              <div class="container">
                  <table class="table table-striped">
                      <thead>
                          <tr>
                              <th scope="col">Title</th>
                              <th scope="col">Description</th>
                              <th colspan="3"></th>
                          </tr>
                      </thead>
                      <tbody>
                        <% @category.each do |category| %>
                            <tr>
                                <td><%= link_to category.title, category_words_path(category) %></td>
                                <td><%= category.description %></td>
                          <% if logged_in? && is_admin? %> 
                                <td><%= link_to raw("<i class='fas fa-pen text-success'></i>"), edit_category_path(category) %></td>
                                <td><%= link_to raw("<i class='fa fa-trash text-danger'></i>"),  category_path(category), method: :delete, data: { confirm: "You sure?" } %></td>
                          <% end %>
                             </tr>
                        <% end %>
                      </tbody>
                  </table>
                    </div>
              </div>
          </div>
      </div>
  </div>
</div>
<div class="row d-flex justify-content-center mt-3">
    <%= will_paginate @category%>   
</div>

app/views/categories/new.html.erb
<%= provide(:title, "Category") %>
<div class="text-center mt-4">
    <h1>Create a new lesson</h1>
</div>
<%= render 'form' %>

app/views/categories/show.html.erb
<h1>categories#show</h1>
<p>Find me in app/views/words/show.html.erb</p>