config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :categories
  resources :lessons
  resources :words
  resources :answers

  resources :categories do
    resources :words
  end

  resources :lessons do
    resources :answers
  end

  root "static_pages#home"
  get "static_pages/home"
  get "/about", to: "static_pages#about"
  get "/contact", to: "static_pages#contact"
  get "/signup", to: "users#new"
  get "/login", to: "sessions#new"
  delete "/logout", to: "sessions#destroy"
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <%= link_to "E-learning", "#", class: "navbar-brand" %>
    <div class="collapse navbar-collapse">
        <ul class="navbar-nav ml-auto">
            <li class="nav-item">
                <%= link_to "Home", root_path, class: "nav-link" %>
            </li>
            <li class="nav-item">
               <%= link_to "About us", about_path, class: "nav-link" %>
            </li>
            <li class="nav-item">
                <%= link_to "Contact", contact_path, class: "nav-link" %>
            </li>
          <% if logged_in? %>
            <li class="nav-item">
                <%= link_to "Start lessons", lessons_path, class: "nav-link" %>
            </li>
          <% end %>
        </ul>
    <div class="form-inline my-2 my-lg-0">
       <ul class="navbar-nav mr-5">
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <% if logged_in? %> <%= current_user.name%> <% else %> Account <% end %>
            </a>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                <% if logged_in? %>
                    <%= link_to "Users List", users_path, class: "dropdown-item" %>
                    <%= link_to "Profile" , current_user, class: "dropdown-item" %>
                    <%= link_to "Settings", edit_user_path(current_user), class: "dropdown-item" %>
            <div class="dropdown-divider"></div>
                    <%= link_to "Logout", logout_path, class: "dropdown-item", method: "delete" %>
                <% else %>
                    <%= link_to "Sign Up", signup_path, class: "dropdown-item" %>
                    <%= link_to "Login", login_path, class: "dropdown-item" %>
                <% end %>
            </div>
          </li>
        </ul>
    </div>
    </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %> | E-Learning System</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%= render 'layouts/header' %>

  <div class="container pt-2">
    <%= render "shared/error_messages" %>
  </div>
  
    <%= yield %>
  </body>
</html>